images/tkg/supported-versions.json

This PR adds support for 1.24.9 K8s and removes older K8s version support.
Closes #10 
With the sandbox build(Image before merging the Bolt MR) I created Photon/Ubunut Node images and tested TKC creation.
Signed-off-by: Dimple Raja Vamsi Kosaraju <kosarajud@vmware.com>

[TKG]Adding support for building 1.24.9 k8s node images

---

images/tkg/README.md
images/tkg/docs/examples/README.md
images/tkg/docs/examples/adding_os_pkg_repos.md
images/tkg/docs/examples/changing_hardware_version.md
images/tkg/docs/examples/configuring_packer_http_port.md
images/tkg/docs/examples/prometheus_node_exporter.md
images/tkg/packer-variables/vsphere.j2

This PR adds documentation for example customization like
- Adding new packages and configuring repositories or sources.
- Changing the VMX version/Hardware version.
- Configuring the Packer HTTP server port during the image build process.
- Adding a new service like Prometheus node exporter.
Other Changes
- Added a gif on how to build the node image.
- Added reference to the packer documentation for permissions of the vSphere user.
Please refer to the [forked repo](https://github.com/DimpleRajaVamsi/vmware-image-builder/tree/doc_add_new_pkgs/images/tkg) for better UX. 
- Made the changes in my forked repo (refer to this [commit](https://github.com/DimpleRajaVamsi/vmware-image-builder/commit/0441ab186bd4a08c8dff5ea4075a6a761ab73da6))
- Built the node image and verified the packages/http …

[Documentation]Adding example customization documents

---

ansible/tasks/photon.yml

This PR fixes https://github.com/vmware/image-builder/issues/19
Adds pos flag pos=1 to kernel parameters to mitigate regression in Pod's Datapath Performance on TKG
Currently, there's a regression in Pod's Datapath performance for the TKG 2.0 TKRs.
Redis throughput degrades by 55%
intra-node TCP bandwidth degrades by 44%
intra-node UDP throughput by 57%
Testing
-  Built the Photon and Ubuntu OVA's
-  Able to get TKC up and running
- Ran gce2e with combinations
- Photon, Antrea
- Photon, Calico
- Ubuntu, Antrea
- Ubuntu, Calico

adds POS flag pos=1 to kernel command line parameters 

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
docs/examples/tutorial_building_an_image.md

Updating the Project name from `VMware Image Builder` to `vSphere Tanzu Kubernetes Grid Image Builder`
Fixes #23

Updating the project name in the docs

---

supported-versions.json

Verified stage and prod images are the same
```
kosarajud@kosarajudDXJW3:~$ imgpkg tag resolve -i projects.registry.vmware.com/tkg/tkg-vsphere-linux-resource-bundle:v1.24.9_vmware.1-tkg.1
projects.registry.vmware.com/tkg/tkg-vsphere-linux-resource-bundle@sha256:9dcec246657fa7cf5ece1feab6164e200c9bc82b359471bbdec197d028b8e577
Succeeded
kosarajud@kosarajudDXJW3:~$ imgpkg tag resolve -i projects-stg.registry.vmware.com/tkg/tkg-vsphere-linux-resource-bundle:v1.24.9_vmware.1-tkg.1
projects-stg.registry.vmware.com/tkg/tkg-vsphere-linux-resource-bundle@sha256:9dcec246657fa7cf5ece1feab6164e200c9bc82b359471bbdec197d028b8e577
Succeeded
```
- Generated both Photon and Ubuntu Images
- Ran gce2e for both Photon and Ubuntu Images
Fixes #27 
Signed-off-by: Dimple Raja Vamsi Kosaraju …

Updating the artifacts bundle image from stg to prod registry

---

Dockerfile
build-ova.sh
hack/make-helpers/build-node-image.sh
supported-versions.json

Currently, the image-builder commit ID is being set in the docker file to a static value, which remains constant regardless of the kubernetes version.
There may be some dependencies on the commit ID to be chosen as per the kubernetes version.
```
make build-node-image OS_TARGET=photon-3 KUBERNETES_VERSION=v1.24.9+vmware.1 TKR_SUFFIX=byoi ARTIFACTS_CONTAINER_IP=10.215.97.148 IMAGE_ARTIFACTS_PATH=/root/image_changes
sha256:50f80e611a6a9b407a4ae934bec77f1fc9f3ca62a1440bab555db4edb12ec42b
Using default port for artifacts container 8081
52d1ed2159d2c3466344dec767f274a877b9b7be2fc45a672122f0316bfffc7e
Hint: Use "docker logs -f v1.24.9---vmware.1-photon-3-image-builder" to see logs and status
Hint: Node Image OVA can be found at /root/image_changes/ovas/
```
With this change, the image-builder …

[TKG]Support custom k8s image builder commit ID per supported Kubernetes version

---

README.md
docs/examples/tutorial_building_an_image.md

This PR has the below changes
- Updated the system requirements like `jq`, `docker`, and `make` to address #32 
- Updated the tutorial doc and some minor changes as per the markdown linter. This address the documentation found in #34 (Please refer to this update https://github.com/vmware-tanzu/vsphere-tanzu-kubernetes-grid-image-builder/issues/34#issuecomment-1571838125)
Fixes: #34 
Fixes: #32 
Signed-off-by: Dimple Raja Vamsi Kosaraju <kosarajud@vmware.com>

Updating the system requirements and tutorial doc

---

ansible/files/scripts/image_retag.py
ansible/tasks/retag_images.yml
scripts/tkg_byoi.py

This PR will bring in the following changes:
1. Modify update_cbt function to add a check before updating `secretRef` in ClusterBootstrapTemplate Config.
2. Remove the --rm flag from ctr functions , since --rm and --d flag cannot be used together for container version v1.16.8 and above.
Closes issue #36 
Testing Done:
1. Updated the artifacts bundle for 1.25.7
2. Validated creation of 1.25.7 OVA and creation of TKC
3. Validated the existing workflow for 1.24.9 OVA and creation of TKC out of it
Signed-off-by: Rida Zuber <ridaz@vmware.com>

Modify update_cbt function and remove --rm flag to support k8s 1.25.7

---

ansible/tasks/photon.yml
ansible/templates/etc/containerd/config_v2.toml
scripts/utkg_custom_ovf_properties.py

This PR has the below changes
- Bump the cloud-init version from 19.4 to 22.4.2
- Use systemd cgroup driver for containerd (Upstream already uses systemd cgroup driver for containerd)
- Disable cgroups kernel memory account and disable cgroups v2 for Photon (Photon grub command line changes)
All the above changes are applicable for both 1.24 and 1.25(In progress)
Fixes #42 
- Built Photon/Ubuntu 1.24/1.25 Images
- gce2e for Photon 1.24.9 (gce2e#8926) 🟢 
- gce2e for Photon 1.25.7 (gce2e#8927) 🟢 
- gce2e for Ubuntu 1.24.9 (gce2e#8942) 🟢 
- gce2e for Ubuntu 1.25.7 (gce2e#8935) 🟢 
- Live cluster verification details
```
root@cc-2zbsx-n28qq [ ~ ]# cat /boot/photon.cfg
photon_cmdline=init=/lib/systemd/systemd rcupdate.rcu_expedited=1 rw systemd.show_status=0 quiet noreplace-smp …
```

Bump cloud init version, use systemd cgroup for containerd and disable cgroup kernel memory accounting

---

supported-versions.json

Issue: #48 
This PR will add the support for TKR version 1.25.7 (Photon/Ubuntu) with the artifacts bundle image and image builder commit details.
```
make list-versions
Kubernetes Version  |  Supported OS
v1.24.9+vmware.1  |  [photon-3,ubuntu-2004-efi]
v1.25.7+vmware.3  |  [photon-3,ubuntu-2004-efi]
Hint: Use "make run-artifacts-container KUBERNETES_VERSION=<version>" to run the artifacts container.
```

Update supported-versions.json with k8s version 1.25.7

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Adding GitHub Issue and PR templates.
Most of the template is copy paste from either [image-builder](https://github.com/kubernetes-sigs/image-builder/) or vm-operator](https://github.com/vmware-tanzu/vm-operator/) Issue/PR templates with some minor modification as required for vSphere TKG image builder.
To view the templates after rendering go to [`gh-issue-pr-tpl` branch](https://github.com/DimpleRajaVamsi/vsphere-tanzu-kubernetes-grid-image-builder/tree/gh-issue-pr-tpl/.github)
Fixes: #54 
Signed-off-by: Dimple Raja Vamsi Kosaraju <kosarajud@vmware.com>

Adding GitHub Issue and PR templates

---

goss/goss-kernel-params.yaml
goss/goss-vars.yaml
packer-variables/default-args.j2

Update linux kernal parameters and install packages
What does this PR do, and why is it needed?
- modifies the kernel from linux-esx to linux + linux-devel
- Install packages on photon images net-tools, curl,tar,open-vm-tools,libseccomp,cloud-init,sysstat,jq,conntrack and update Goss tests
**Which issue(s) is/are addressed by this PR?
Fixes #51 
Testing Done:
Generated Photon/Ubuntu 1.24.9 and 1.25.7 Images
root@ubuntuguest:/home/ubuntu/vsphere-tanzu-kubernetes-grid-image-builder# ls -ltr /Users/image/ovas/
total 11058416
-rw-r--r-- 1 root root 3456230400 Aug  7 10:04 photon-3-amd64-v1.24.9---vmware.1-byoi.ova
-rw-r--r-- 1 root root 4411801600 Aug  7 11:41 ubuntu-2004-amd64-v1.24.9---vmware.1-byoi.ova
-rw-r--r-- 1 root root 3455770112 Aug  7 12:50 …

Update linux kernal parameters and install packages

---

supported-versions.json

Add 1.26.5 Support
This PR will add the support for TKR version 1.25.7 (Photon/Ubuntu) with the artifacts bundle image and image builder commit details.
make list-versions
Kubernetes Version  |  Supported OS
v1.24.9+vmware.1  |  [photon-3,ubuntu-2004-efi]
v1.25.7+vmware.3-fips.1  |  [photon-3,ubuntu-2004-efi]
v1.26.5+vmware.2-fips.1  |  [photon-3,ubuntu-2004-efi]
**Which issue(s) is/are addressed by this PR?** *
Fixes #58 
**Testing Done**:
make list-versions
Kubernetes Version  |  Supported OS
v1.24.9+vmware.1  |  [photon-3,ubuntu-2004-efi]
v1.25.7+vmware.3-fips.1  |  [photon-3,ubuntu-2004-efi]
v1.26.5+vmware.2-fips.1  |  [photon-3,ubuntu-2004-efi]

Add 1.26.5 Support

---

Dockerfile
Makefile
README.md
build-ova.sh
docs/examples/adding_os_pkg_repos.md
hack/make-helpers/build-image-builder-container.sh
hack/make-helpers/build-node-image.sh
hack/make-helpers/utils.sh
supported-versions.json

With https://github.com/vmware-tanzu/vsphere-tanzu-kubernetes-grid-image-builder/pull/33 git checkout will happen during the image build process and recently there has been a change in the upstream(https://github.com/kubernetes-sigs/image-builder/commit/a299f46009691d65a8b0505c85e92084d107b320) that bumps Ansible and changes the minimum supported Python version to 3.9.
We use [Photon 3.0](https://github.com/vmware-tanzu/vsphere-tanzu-kubernetes-grid-image-builder/blob/main/Dockerfile#L4) in the container image and it only supports 3.7. Ideally, we shouldn't be syncing the code to the latest we should be syncing the code the `image-builder-commit-id` that has been tested during the build process so that we will not hit any issues with `make …

Bump ansible version and download packer using deps-ova target

---

supported-versions.json

With decomissioning of projects.registry.vmware.com, we need to update the location from where the artifat images will be pulled
✅ Closes: #75

Update the registry to pull artifact images from new registry location for broadcom

---

scripts/tkg_byoi.py

Currently gateway-api package is included in the list of addon packages to be installed regardless of TKR version. It should not be installed on TKR versions <v1.27 as gateway package is not available on these versions.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
**Testing Done**:
**Are there any special notes for your reviewer**:

Fix package discovery logic for gateway-api package

---

supported-versions.json

* Add support for building 1.28.8 images
* Removes support for building 1.25.7 images
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
* Adds support for building Photon-5 based CAPI images (Supported only with v1.28.8 TKR)

Add support for building 1.28.8 images

---

supported-versions.json

What does this PR do, and why is it needed?
Add support for building 1.29.4 images
Which issue(s) is/are addressed by this PR? (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Adds support for building Photon-5 based CAPI images (Supported only with v1.29.4 TKR)

Add support for building 1.29.4 images

---

packer-variables/windows/default-args-windows.j2

Remove a duplicate argument from `default-args-windows.j2` which is set in both `default-args-windows.j2` and `goss-args-windows.j2`

Remove duplicate argument goss_inspect_mode for Windows build

---

ansible/tasks/retag_images.yml

This change will help to keep versions in sync with artifact server.

Remove hardcoded version of docker-registry image

---

supported-context.json

Update to the latest image builder commit to include fixes for windows credentials(allow customer to bootstrap password for administrator).

Update to latest upstream IB commit for windows fixes

---

Dockerfile

When building a Windows image and running the 'make build-node-image' command, the Docker build was failing at the 'make deps-ova' command due to the image missing the pywinrm module
**Which issue(s) is/are addressed by this PR?** * `fixes #96 ` format, will close the issue(s) when PR gets merged)*:
Fixes #96 
**Testing Done**:
Multiple builds completed with fix and then removal of fix to get the error back
**Are there any special notes for your reviewer**:

Fixed missing py module pywinrm impacting 'make deps-ova'
